name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cf.deb
          sudo dpkg -i cf.deb

      - name: Configure SSH with Cloudflare Access Service Token
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          cat <<EOF > ~/.ssh/config
          Host ssh.asyhar.fun
            ProxyCommand cloudflared access ssh --hostname %h
          EOF

      - name: Deploy via rsync
        run: |
          set -e

          echo "Setting up SSH..."
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=accept-new  -i ~/.ssh/id_rsa root@ssh.asyhar.fun

          echo "Running rsync deployment..."
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=accept-new" \
            ./ root@ssh.asyhar.fun:/var/www/nixmart/
          echo "Deployment complete."
